enum MutationTypes {
  // App
  APP_DATA_LOADED = 'APP_DATA_LOADED',

  // Devices
  DEVICES_MAP_UPDATE = 'DEVICES_MAP_UPDATE',
  DEVICES_SAVE_OK = 'DEVICES_SAVE_OK',
  DEVICES_ADD_OK = 'DEVICES_ADD_OK',
  DEVICES_DELETE_OK = 'DEVICES_DELETE_OK',
  DEVICES_ACTIVE_UPDATE = 'DEVICES_ACTIVE_UPDATE',

  // Robo
  ROBO_INIT = 'ROBO_INIT',
  ROBO_STOP = 'ROBO_STOP',
  ROBO_SAY = 'ROBO_SAY',
  ROBO_PAUSE = 'ROBO_PAUSE',
  ROBO_RESUME = 'ROBO_RESUME',
  ROBO_EMOTION_CHANGE = 'ROBO_EMOTION_CHANGE',

  // Settings
  SETTINGS_UPDATE = 'SETTINGS_UPDATE',

  // Home state
  HOME_STATE_UPDATE = 'HOME_STATE_UPDATE',

  // User
  USER_TOKEN_SET = 'USER_TOKEN_SET',
  USER_TOKEN_CLEAR = 'USER_TOKEN_CLEAR',
  USER_DATA_SET = 'USER_DATA_SET',
  USER_DATA_UPDATE = 'USER_DATA_UPDATE',
  USER_DATA_CLEAR = 'USER_DATA_CLEAR',

  // Users
  USERS_MAP_UPDATE = 'USERS_MAP_UPDATE',
  USERS_MAP_ADD = 'USERS_MAP_ADD',
  USERS_MAP_REMOVE = 'USERS_MAP_REMOVE',

  // WS
  WS_CONNECT = 'WS_CONNECT',
  WS_CONNECTED = 'WS_CONNECTED',
  WS_DISCONNECT = 'WS_DISCONNECT',
  WS_DISCONNECTED = 'WS_DISCONNECTED',
  WS_MESSAGE_SEND = 'WS_MESSAGE_SEND',
  WS_MESSAGE_SENT = 'WS_MESSAGE_SENT',
  WS_MESSAGE_RECEIVED = 'WS_MESSAGE_RECEIVED',
}

export default MutationTypes;
